extends: [ react-app, airbnb ]
parser: babel-eslint
env:
  browser: true
  node: true
  mocha: true

rules:
  react/jsx-filename-extension: [ 1, { "extensions": [".js", ".jsx"] } ]
  react/forbid-prop-types: 0
  react/no-multi-comp: 0
  import/default: 0
  import/no-duplicates: 0
  import/named: 0
  import/namespace: 0
  import/no-unresolved: 0
  import/no-named-as-default: 2
  comma-dangle: 0
  indent: [ 2, 2, { SwitchCase: 1 } ]
  no-console: 0
  no-alert: 0
  no-unused-vars: 1

  no-underscore-dangle: 0
  global-require: 0

  flow-vars/define-flow-type: 1
  flow-vars/use-flow-type: 1

plugins:
  - react
  - jsx-a11y
  - flow-vars
  - import

settings:
  import/parser: babel-eslint
  import/resolve:
    moduleDirectory:
    - node_modules
    - app
  import/ignore:
    - \.(scss|less|css)$